BigQueryCloudFunctionsUrl = "https://us-central1-chatbot-319108.cloudfunctions.net/eventToBigQuery"
GCF_service_account_credentials = "cloudFunctionFullAccessKey.json"
FS_service_account_credentials = "firebase_key.json"

projectName = "TestingData"
# collectionName = "chatbot2021"
dbName = "EpidemicPreventionDB"
siteTable = "sites"
userTable = "users"
footPrintTable = "footprints"